# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelParams = [
    "mem_sleep_default=deep"
    "pcie_aspm.policy=powersupersave"
  ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/801303fb-262c-4890-b9ca-946be59dc1c3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A6C-11C9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/DarkJaguar" = {
    device = "/dev/disk/by-uuid/80BE7B5EBE7B4BA2";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" ];
  };

  swapDevices = [ ];

  services = {
    asusd = {
      enable = true;
      enableUserService = true;
    };
    udev = {
        extraHwdb = ''
        # Fixes mic mute button
        evdev:name:*:dmi:bvn*:bvr*:bd*:svnASUS*:pn*:*
        KEYBOARD_KEY_ff31007c=f20
        '';
    };
  };

  #flow devices are 2 in 1 laptops
  hardware.sensor.iio.enable = true;

  # Meditek doesn't seem to be quite sensitive enough on the default roaming settings:
  #   https://wiki.archlinux.org/title/Wpa_supplicant#Roaming
  #   https://wiki.archlinux.org/title/Iwd#iwd_keeps_roaming
  #
  # But NixOS doesn't have the tweaks for IWD, yet.
  networking.wireless.iwd.settings = {
    General = {
      RoamThreshold = -75;
      RoamThreshold5G = -80;
      RoamRetryInterval = 20;
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp198s0f4u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
