# More options: https://github.com/DreamMaoMao/mango/wiki/

# Autostart
exec=noctalia-shell

# Sources
source=/home/brandon/.config/mango/noctalia.conf
source=/home/brandon/.config/mango/style.conf
source=/home/brandon/.config/mango/animations.conf
source=/home/brandon/.config/mango/keybinds.conf
source=/home/brandon/.config/mango/rules.conf

# Master-stack layout
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0

# Scroller layout
scroller_structs=20
scroller_default_proportion=0.8
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Overview
hotarea_size=10
enable_hotarea=1
overviewgappi=5
overviewgappo=30

# Misc
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_tag=1
cursor_size=24
drag_tile_to_tile=1
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
snap_distance=30

# Keyboard
repeat_rate=25
repeat_delay=600
xkb_rules_layout=us

# Trackpad
tap_to_click=1
tap_and_drag=1
drag_lock=1
disable_while_typing=1
swipe_min_threshold=1

# This sources the noctalia theme
source = /home/brandon/.config/mango/noctalia.conf

