# Window rules
windowrule=appid:brave-browser,tags:2
windowrule=appid:steam,tags:3
windowrule=appid:steam_app_.*,tags:3

# Layer rules
layerrule=animation_type_open:zoom,layer_name:noctalia
layerrule=animation_type_close:zoom,layer_name:noctalia
