[colors]
background = "#1c2022FF"
text_primary = "#e0e3e4FF"
text_muted = "#bec8ccFF"
accent_primary = "#86d1e9FF"
accent_secondary = "#afcbd5FF"
warning = "#e0b8f5FF"
error = "#ffb4abFF"
insert_hint = "#e0b8f580"
backdrop = "#3f484cFF"

[colors.border]
focused = "#86d1e9FF"
unfocused = "#3f484cFF"
outer = "#101415FF"

[colors.overview]
background_tint = "#10141588"
badge = "#86d1e9FF"
workspace_background = "#101415FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#e0b8f5FF"
border_color_unfocused = "#b18bc5FF"
