[colors]
background = "#1e1f29FF"
text_primary = "#e3e1f0FF"
text_muted = "#c6c4daFF"
accent_primary = "#bfc1ffFF"
accent_secondary = "#bfc1ffFF"
warning = "#f8acffFF"
error = "#ffb4abFF"
insert_hint = "#f8acff80"
backdrop = "#454557FF"

[colors.border]
focused = "#bfc1ffFF"
unfocused = "#454557FF"
outer = "#12121dFF"

[colors.overview]
background_tint = "#12121d88"
badge = "#bfc1ffFF"
workspace_background = "#12121dFF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#f8acffFF"
border_color_unfocused = "#810098FF"
