config_version = 7

[audio]
enable_overdrive = true

[bar.default]
center = [ "workspaces", "audio_visualizer", "weather" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_ends = 0
start = [ "control-center", "clock", "group:g1", "media" ]

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "wallpaper", "mpvpaper", "launcher_2" ]
    opacity = 0.20000000298023224
    padding = 6.0

[calendar]
enabled = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1024.0
    cy = 1161.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[plugin_settings."alexander/game-launcher"]
browser_placement = "attached"
steampoacher_enabled = true

[plugin_settings."h465855hgg/lyrics"]
player_allowlist = [ "spotify" ]
translation_language = "en"

[plugin_settings."noctalia/mpvpaper"]
mpv_options = "vf=fps=30"
video_directory = "~/Videos/Wallpapers"

[plugins]
enabled = [ "noctalia/screen_recorder", "alexander/game-launcher", "noctalia/mpvpaper" ]

[shell.panel]
launcher_placement = "attached"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "opencode", "discord", "neovim", "steam", "bat" ]

[wallpaper]
directory = "/home/brandon/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/brandon/Pictures/Wallpapers/frieren-magical-3840x2160-15165.jpeg"

    [wallpaper.last]
    path = "/home/brandon/.cache/noctalia/mpvpaper/_home_brandon_Videos_Wallpapers_neon_waterfall_moewalls_com_mp4.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/brandon/.cache/noctalia/mpvpaper/_home_brandon_Videos_Wallpapers_neon_waterfall_moewalls_com_mp4.jpg"

[widget.audio_visualizer]
bands = 32
color_1 = "on_primary"
interactive = false
width = 100

[widget.launcher_2]
type = "alexander/game-launcher:launcher"

[widget.media]
hide_when_no_media = true

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.workspaces]
hide_when_empty = true
style = "focus_hint"