color0 #454653
color1 #ffb4ab
color2 #bac3ff
color3 #bdc4f3
color4 #fdaaff
color5 #bac3ff
color6 #bdc4f3
color7 #e3e1eb
color8 #8f909e
color9 #ffb4ab
color10 #bac3ff
color11 #bdc4f3
color12 #fdaaff
color13 #bac3ff
color14 #bdc4f3
color15 #e3e1eb

cursor                #e3e1eb
cursor_text_color     #121319
background            #121319
foreground            #e3e1eb
selection_foreground  #c5c5d5
selection_background  #454653
active_border_color   #bac3ff
inactive_border_color #454653
url_color             #bac3ff

active_tab_foreground   #00208e
active_tab_background   #bac3ff
inactive_tab_foreground #c5c5d5
inactive_tab_background #454653
cursor_trail_color      #c5c5d5
